### ISSUE TITLE
Error , I Powerd it on repil it

### ISSUE THREAD

**Issue by AhmedElguker** [ngregrichardson/clone-bot#6]
yarn run v1.22.19
$ yarn compile && node dist/app.js
$ rimraf dist && tsc
/home/runner/clone-bot/dist/utils/utils.js:10
    let output = variable.trim().replaceAll("\\n", "\n");
                          ^

TypeError: Cannot read properties of undefined (reading 'trim')
    at formatEnvironmentVariable (/home/runner/clone-bot/dist/utils/utils.js:10:27)
    at initializeFirebase (/home/runner/clone-bot/dist/utils/utils.js:25:62)
    at Object.<anonymous> (/home/runner/clone-bot/dist/app.js:19:32)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47

Node.js v18.12.1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
~/clone-bot$ yarn start
yarn run v1.22.19
$ yarn compile && node dist/app.js
$ rimraf dist && tsc
/home/runner/clone-bot/dist/utils/utils.js:10
    let output = variable.trim().replaceAll("\\n", "\n");
                          ^

TypeError: Cannot read properties of undefined (reading 'trim')
    at formatEnvironmentVariable (/home/runner/clone-bot/dist/utils/utils.js:10:27)
    at initializeFirebase (/home/runner/clone-bot/dist/utils/utils.js:25:62)
    at Object.<anonymous> (/home/runner/clone-bot/dist/app.js:19:32)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47

Node.js v18.12.1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by ngregrichardson** [comment]
Have you set up the correct Firebase environment variables? I realize that the README doesn't list them as required but you need to create a Firebase project and add the environment variables:
- `FIREBASE_PROJECT_ID`
- `FIREBASE_PRIVATE_KEY`
- `FIREBASE_CLIENT_EMAIL`

Also, this has not been updated to the latest Discord APIs and is not planned to be, so some of the APIs may be different and it probably won't be fixed.

**Comment by ngregrichardson** [comment]
Closing this, please re-open if that doesn't solve your issue :)
